CineArte/CineArte-war/src/java/com/cinearte/app/mb/SalaMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinearte.app.mb;

import com.cinearte.app.cdi.DibujaSalaCDI;
import com.cinearte.app.dto.AsientoDTO;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Axel
 */
@Named("salaMB")
@SessionScoped
public class SalaMB implements Serializable {

    @Inject
    DibujaSalaCDI dibujaSala;
    private int idFuncion;
    private DataModel dataTable;

    public void preparaSala() {
        dibujaSala.init(idFuncion);
        dataTable = new ListDataModel(getMapaSala());
    }

    public void selectAsiento(AsientoDTO asiento) {
        System.out.println("Vamos a usar este asiento:" + asiento);
    }
    
    public void preparaSalaByIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
        dibujaSala.init(idFuncion);
        dataTable = new ListDataModel(getMapaSala());
    }

    public DataModel getDataTable() {
        return dataTable;
    }

    public void setDataTable(DataModel dataTable) {
        this.dataTable = dataTable;
    }

    public int getIdFuncion() {
        return idFuncion;
    }

    public void setIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
    }

    public List<List<AsientoDTO>> getMapaSala() {
        return dibujaSala.getMapaSala();
    }

}

CineArte/CineArte-war/src/java/com/cinearte/app/mb/UtilMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinearte.app.mb;

import com.cinearte.app.ejb.CompraEJB;
import java.io.Serializable;
import java.util.Date;
import java.util.Random;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author edivargas
 */
@Named(value = "utilMB")
@RequestScoped
public class UtilMB implements Serializable {

    @EJB
    CompraEJB compraEJB;
    @Inject
    UserSession userSession;

    // private String theme = "styled-select"; for v1
    /**
     * Creates a new instance of UtilMB
     */
    public UtilMB() {
    }

    @PostConstruct
    public void selectTheme() {
        // Para index_v1.xhtml descomentar las sig lineas
        //if (new Random().nextBoolean()) {
        //    theme = "other";
        //}
        // Para ese ejercicio es necesario mantener 
        // una variable theme en esta clase
    }

    public String getFecha() {
        return new Date().toString();
    }

    public void procesaDatosListener(ActionEvent event) {
        System.out.println("Desde el Listener procesaDatosListener");
        System.out.println("User:" + userSession.getUser()
                + ":Password:" + userSession.getPassword());
        compraEJB.compra();
    }

    public String procesaDatos() {
        System.out.println("Desde el Action procesaDatosListener");
        return userSession.getSelectedPage();
        //return null;
    }

    public void signin(ActionEvent event) {
        if (userSession.getUser().equals(userSession.getPassword())) {
            userSession.setSigned(true);
        } else {
            userSession.setSigned(false);
        }
    }

    public void signoff(ActionEvent event) {
        userSession.setSigned(false);
    }

    public String navega(String origen) {
        if ("login".equals(origen)) {
            if (userSession.isSigned()) {
                return "/menu";
            } else {
                return null;
            }
        } else {
            if (userSession.isSigned()) {
                return "/menu";
            }
        }
        return "/login";
    }

    public void changeValue(ValueChangeEvent event) {
        System.out.println("Evento:" + event);
        //Registra el cambio
    }

    public boolean isRendered() {
        return new Random().nextBoolean();
    }

}

CineArte/CineArte-war/web/index_v1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <style>
            /* -------------------- Page Styles (not required) */
            div { margin: 20px; }

            /* -------------------- Select Box Styles: bavotasan.com Method (with special adaptations by ericrasch.com) */
            /* -------------------- Source: http://bavotasan.com/2011/style-select-box-using-only-css/ */
            .styled-select {
                background: url(http://i62.tinypic.com/15xvbd5.png) no-repeat 96% 0;
                height: 29px;
                overflow: hidden;
                width: 240px;
            }

            .styled-select select {
                background: transparent;
                border: none;
                font-size: 14px;
                height: 29px;
                padding: 5px; /* If you add too much padding here, the options won't show in IE */
                width: 268px;
            }

            .styled-select.slate {
                background: url(http://i62.tinypic.com/2e3ybe1.jpg) no-repeat right center;
                height: 34px;
                width: 240px;
            }

            .styled-select.slate select {
                border: 1px solid #ccc;
                font-size: 16px;
                height: 34px;
                width: 268px;
            }

            /* -------------------- Rounded Corners */
            .rounded {
                -webkit-border-radius: 20px;
                -moz-border-radius: 20px;
                border-radius: 20px;
            }

            .semi-square {
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
            }

            /* -------------------- Colors: Background */
            .slate   { background-color: #ddd; }
            .green   { background-color: #779126; }
            .blue    { background-color: #3b8ec2; }
            .yellow  { background-color: #eec111; }
            .black   { background-color: #000; }

            /* -------------------- Colors: Text */
            .slate select   { color: #000; }
            .green select   { color: #fff; }
            .blue select    { color: #fff; }
            .yellow select  { color: #000; }
            .black select   { color: #fff; }


            /* -------------------- Select Box Styles: danielneumann.com Method */
            /* -------------------- Source: http://danielneumann.com/blog/how-to-style-dropdown-with-css-only/ */
            #mainselection select {
                border: 0;
                color: #EEE;
                background: transparent;
                font-size: 20px;
                font-weight: bold;
                padding: 2px 10px;
                width: 378px;
                *width: 350px;
                *background: #58B14C;
                -webkit-appearance: none;
            }

            #mainselection {
                overflow:hidden;
                width:350px;
                -moz-border-radius: 9px 9px 9px 9px;
                -webkit-border-radius: 9px 9px 9px 9px;
                border-radius: 9px 9px 9px 9px;
                box-shadow: 1px 1px 11px #330033;
                background: #58B14C url("http://i62.tinypic.com/15xvbd5.png") no-repeat scroll 319px center;
            }


            /* -------------------- Select Box Styles: stackoverflow.com Method */
            /* -------------------- Source: http://stackoverflow.com/a/5809186 */
            select#soflow, select#soflow-color {
                -webkit-appearance: button;
                -webkit-border-radius: 2px;
                -webkit-box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.1);
                -webkit-padding-end: 20px;
                -webkit-padding-start: 2px;
                -webkit-user-select: none;
                background-image: url(http://i62.tinypic.com/15xvbd5.png), -webkit-linear-gradient(#FAFAFA, #F4F4F4 40%, #E5E5E5);
                background-position: 97% center;
                background-repeat: no-repeat;
                border: 1px solid #AAA;
                color: #555;
                font-size: inherit;
                margin: 20px;
                overflow: hidden;
                padding: 5px 10px;
                text-overflow: ellipsis;
                white-space: nowrap;
                width: 300px;
            }

            select#soflow-color {
                color: #fff;
                background-image: url(http://i62.tinypic.com/15xvbd5.png), -webkit-linear-gradient(#779126, #779126 40%, #779126);
                background-color: #779126;
                -webkit-border-radius: 20px;
                -moz-border-radius: 20px;
                border-radius: 20px;
                padding-left: 15px;
            }
        </style>
    </h:head>
    <h:body>
        Hello from Facelets
        <br/><br/>
        <h:form id="principalForm">
            <h:outputLabel id="userLabel" value="Usuario:" for="user" />
            <h:inputText  id="user" 
                          alt="User" title="User"
                          value="#{userSession.user}"
                          />
            <br/>
            <h:outputText id="passwordLabel" value="Esto es un ejemplo de password input"  />
            <h:inputSecret  id="password" label="Password" 
                            alt="Password" title="Password"
                            value="#{userSession.password}"
                            onclick="alert('Esto es secreto... recuerdalo');"
                            />
            <br/>
            <h:outputLabel id="valorLabel"  
                           value="Valor X (entre 10 y 20):" 
                           for="principalForm:valor"/>
            <h:inputText id="valor" size="20" maxlength="12" 
                         title="Valor Title" alt="Valor Alt"
                         label="Valor Y"
                         valueChangeListener="#{utilMB.changeValue}"
                         required="true" 
                         lang="es"
                         requiredMessage="Es requerido el valor, no tiene nada, ponle algo"
                         >
                <f:validateLongRange minimum="10" maximum="20" for="valor"/>
            </h:inputText>
            <br/>
            <h:outputText id="tipoSalaLabel"  value="Selecciona el Tipo de Sala:" />
            <h:selectOneMenu value="#{userSession.selected}"  
                             class="#{utilMB.theme}" >
                <f:selectItems value="#{cacheEJB.tipoSalas}" var="tipoSala" 
                               itemValue="#{tipoSala.idTipoSala}" 
                               itemLabel="#{tipoSala.descripcion}"
                               itemDescription="#{tipoSala.toString()}"/>
            </h:selectOneMenu>
            <br/>
            <h:outputText id="destinoLabel"  value="Selecciona la pagina siguiente:" />
            <h:selectOneMenu value="#{userSession.selectedPage}" >
                <f:selectItem itemValue="modulo1/Pagina1" itemLabel="Pagina 1" />
                <f:selectItem itemValue="/modulo1/Pagina2" itemLabel="Pagina 2" />
            </h:selectOneMenu>
            <br/><br/>
            <h:commandButton id="actionNadaBtn"  
                             value="No hace nada"
                             actionListener="#{utilMB.procesaDatosListener}"
                             action="#{utilMB.procesaDatos}"/>
            <h:commandButton id="cancelBtn"  immediate="true"
                             value="Cancelar" />
        </h:form>
        <br/>
        <h:outputText value="La fecha es #{utilMB.fecha}" />
        <br/>
        <h:outputText value="El id seleccionado es #{userSession.selected}" />
        <br/>
        <h:outputText value="El objecto seleccionado es #{cacheEJB.getTipoSalaById(userSession.selected)}" />
        <br/>
    </h:body>
</html>

CineArte/CineArte-war/web/index_v2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="#{utilMB.theme}" name="principal.css" />
    </h:head>
    <h:body>
        Hello from Facelets
        <br/><br/>
        <h:form id="principalForm">
            <h:commandButton id="darkStyleBtn"  immediate="true"
                             value="Dark Style" 
                             actionListener="#{utilMB.setTheme('dark')}"
                             />
            <h:commandButton id="lightStyleBtn"  immediate="true"
                             value="Light Style" 
                             actionListener="#{utilMB.setTheme('light')}"
                             />

            <h:outputLabel id="userLabel" value="Usuario:" for="user" />
            <h:inputText  id="user" 
                          alt="User" title="User"
                          value="#{userSession.user}"
                          />
            <br/>
            <h:outputText id="passwordLabel" value="Esto es un ejemplo de password input"  />
            <h:inputSecret  id="password" label="Password" 
                            alt="Password" title="Password"
                            value="#{userSession.password}"
                            />
            <br/>
            <h:outputLabel id="valorLabel"  
                           value="Valor X (entre 10 y 20):" 
                           for="principalForm:valor"/>
            <h:inputText id="valor" size="20" maxlength="12" 
                         title="Valor Title" alt="Valor Alt"
                         label="Valor Y"
                         valueChangeListener="#{utilMB.changeValue}"
                         required="true" 
                         lang="es"
                         requiredMessage="Es requerido el valor, no tiene nada, ponle algo"
                         >
                <f:validateLongRange minimum="10" maximum="20" for="valor"/>
            </h:inputText>
            <br/>
            <h:outputText id="tipoSalaLabel"  value="Selecciona el Tipo de Sala:" />
            <h:selectOneMenu value="#{userSession.selected}"
                             >
                <f:selectItems value="#{cacheEJB.tipoSalas}" var="tipoSala" 
                               itemValue="#{tipoSala.idTipoSala}" 
                               itemLabel="#{tipoSala.descripcion}"
                               itemDescription="#{tipoSala.toString()}"/>
            </h:selectOneMenu>
            <br/>
            <h:outputText id="destinoLabel"  value="Selecciona la pagina siguiente:" />
            <h:selectOneMenu value="#{userSession.selectedPage}" >
                <f:selectItem itemValue="modulo1/Pagina1" itemLabel="Pagina 1" />
                <f:selectItem itemValue="/modulo1/Pagina2" itemLabel="Pagina 2" />
            </h:selectOneMenu>
            <br/><br/>
            <h:commandButton id="actionNadaBtn"  
                             value="No hace nada"
                             actionListener="#{utilMB.procesaDatosListener}"
                             action="#{utilMB.procesaDatos}"/>
            <h:commandButton id="cancelBtn"  immediate="true"
                             value="Cancelar" />
        </h:form>
        <br/>
        <h:outputText value="La fecha es #{utilMB.fecha}" />
        <br/>
        <h:outputText value="El id seleccionado es #{userSession.selected}" />
        <br/>
        <h:outputText value="El objecto seleccionado es #{cacheEJB.getTipoSalaById(userSession.selected)}" />
        <br/>
    </h:body>
</html>

CineArte/CineArte-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{bundleMsg.app_title}</title>
        <h:outputStylesheet 
            library="#{userSession.theme}" 
            name="principal.css" />
    </h:head>
    <h:body>
        <h:panelGrid columns="2">
            <h:graphicImage id="logoImg" library="#{userSession.theme}"
                            name="#{bundleMsg.app_logo}" />
            <h:outputText id="welcomeLabel" 
                          value="#{bundleMsg.app_welcome}" />
        </h:panelGrid>        
        <br/><br/>
        <h:form id="principalForm">
            <h:commandButton id="darkStyleBtn"  immediate="true"
                             value="#{bundleMsg.user_theme_dark}" 
                             actionListener="#{userSession.setTheme('dark')}"
                             />
            <h:commandButton id="lightStyleBtn"  immediate="true"
                             value="#{bundleMsg.user_theme_light}" 
                             actionListener="#{userSession.setTheme('light')}"
                             />
            <br/>
            <br/><h:commandButton id="englishBtn"  immediate="true"
                             value="#{bundleMsg.user_lang_en}" 
                             actionListener="#{userSession.setLanguage('en')}"
                             />
            <h:commandButton id="spanishBtn"  immediate="true"
                             value="#{bundleMsg.user_lang_es}" 
                             actionListener="#{userSession.setLanguage('es')}"
                             />
            <br/>
            <br/>
            <h:outputLabel id="userLabel" 
                           value="#{bundleMsg.login_user} " for="user" />
            <h:inputText  id="user" 
                          alt="#{bundleMsg.login_user}" 
                          title="#{bundleMsg.login_user}"
                          value="#{userSession.user}"
                          required="true"
                          requiredMessage="#{bundleMsg.login_user_required}"
                          />
            <br/>
            <h:outputText id="passwordLabel" 
                          value="#{bundleMsg.login_password} " />
            <h:inputSecret  id="password" 
                            label="#{bundleMsg.login_password}" 
                            alt="#{bundleMsg.login_password}" 
                            title="#{bundleMsg.login_password}"
                            value="#{userSession.password}"
                            required="true"
                            requiredMessage="#{bundleMsg.login_password_required}"
                            />
            <br/>
            <h:commandButton id="firmarBtn"  
                             value="#{bundleMsg.login_firmar_btn}"
                             actionListener="#{utilMB.signin}"
                             action="#{utilMB.navega('login')}"
                             />
            <h:commandButton id="cancelBtn"  
                             immediate="true"
                             value="#{bundleMsg.login_cancelar_btn}" />
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>#{bundleMsg.app_title}</title>
        <h:outputStylesheet library="#{userSession.theme}" name="principal.css" />
    </h:head>
    <h:body>

        <h:panelGrid columns="2">
            <h:graphicImage id="logoImg" library="#{userSession.theme}"
                            name="#{bundleMsg.app_logo}"/>
            <h:outputText id="welcomeLabel" 
                          value="#{bundleMsg.app_welcome}" />
        </h:panelGrid>

        <br/><br/>
        <h:form id="principalForm">
            <h:outputLabel id="rfcLabel" value="RFC" />
            <h:inputText id="rfc" value="#{userSession.rfc}" 
                         converter="rfcConverter"
                         converterMessage="Escribalo con puros guiones"
                         >
                <f:validator  validatorId="rfcValidator"/>
                <f:validateLength minimum="12" maximum="13" for="rfc"/>
            </h:inputText>
            <br/>
            <h:message for="rfc" />
            <br/>
            <br/>
            <h:outputLabel id="valorLabel"  
                           value="#{bundleMsg.menu_valor_x}" 
                           for="principalForm:valor"/>
            <h:inputText id="valor" size="20" maxlength="12" 
                         title="Valor Title" alt="Valor Alt"
                         label="#{bundleMsg.menu_valor_y}"
                         valueChangeListener="#{utilMB.changeValue}"
                         required="true" 
                         lang="es"
                         requiredMessage="#{bundleMsg.menu_valor_x_required}"
                         >
                <f:validateLongRange minimum="10" maximum="20" for="valor"/>
            </h:inputText>
            <br/>
            <h:message for="valor" />
            <br/>
            <br/>
            <h:outputText id="tipoSalaLabel"  value="#{bundleMsg.menu_combo_tipoSala}" />
            <h:selectOneMenu value="#{userSession.selected}"
                             >
                <f:selectItems value="#{cacheEJB.tipoSalas}" var="tipoSala" 
                               itemValue="#{tipoSala.idTipoSala}" 
                               itemLabel="#{tipoSala.descripcion}"
                               itemDescription="#{tipoSala.toString()}"/>
            </h:selectOneMenu>
            <br/>
            <h:outputText id="destinoLabel"  value="#{bundleMsg.menu_combo_Pagina}" />
            <h:selectOneMenu value="#{userSession.selectedPage}" >
                <f:selectItem itemValue="modulo1/Pagina1" itemLabel="#{bundleMsg.menu_combo_Pagina_pagina1}" />
                <f:selectItem itemValue="/modulo1/Pagina2" itemLabel="#{bundleMsg.menu_combo_Pagina_pagina2}" />
            </h:selectOneMenu>
            <br/><br/>
            <h:commandButton id="navegaBtn"  
                             value="#{bundleMsg.menu_navegar}"
                             actionListener="#{utilMB.procesaDatosListener}"
                             action="#{utilMB.procesaDatos}"/>
            <h:commandButton id="salirBtn"  immediate="true"
                             value="#{bundleMsg.menu_logout}"
                             actionListener="#{utilMB.signoff}"
                             action="#{utilMB.navega('menu')}"/>
            <h:commandButton id="verSalaBtn"
                             value="Ver"
                             action="#{utilMB.navega('vistaSala')}"
                             />
        </h:form>
        <h:outputText value="--------" />
        <h:messages globalOnly="true" />
        <h:outputText value="--------" />
        <br/>
        <br/>
        <h:form>
            <h:dataTable id="peliculaTable"
                         value="#{userSession.peliculas}"
                         var="pelicula"
                         rowClasses="oddRows,evenRows"
                         columnClasses="oddColumns,evenColumns _40Column,oddColumns rightColumn _20Column,evenColumns _20Column"
                         headerClass="headerColumn"
                         footerClass="headerColumn"
                         >
                <h:column id="id">
                    <f:facet name="header">Id</f:facet>
                    <h:outputText value="#{pelicula.idPelicula}" />
                    <f:facet name="footer">Id</f:facet>
                </h:column>
                <h:column id="nombre">
                    <f:facet name="header">Nombre</f:facet>
                    <h:commandLink 
                        actionListener="#{salaMB.preparaSalaByIdFuncion(1)}"
                        action="vistaSala">
                        <h:outputText value="#{pelicula.nombrePelicula}" />
                    </h:commandLink>
                    <f:facet name="footer">Nombre</f:facet>
                </h:column>
                <h:column id="duracion">
                    <f:facet name="header">Duracion</f:facet>
                    <h:outputText value="#{pelicula.duracion}" />
                    <f:facet name="footer">Duracion</f:facet>
                </h:column>
                <h:column id="anio">
                    <f:facet name="header">Año</f:facet>
                    <h:outputText value="#{pelicula.anio}" />
                    <f:facet name="footer">Año</f:facet>
                </h:column>
                <h:column>
                    <h:graphicImage 
                        id="logoImg"
                        class="logoImg2"
                        library="#{userSession.theme}"
                        name="#{bundleMsg.app_logo}"/>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/modulo1/Pagina1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{bundleMsg.app_title}</title>
        <h:outputStylesheet library="#{userSession.theme}" name="principal.css" />
    </h:head>
    <h:body>
        <h:panelGrid columns="2">
            <h:graphicImage id="logoImg" library="#{userSession.theme}"
                            name="#{bundleMsg.app_logo}">
            </h:graphicImage>
            <h:outputText id="welcomeLabel" 
                          value="#{bundleMsg.pagina1_welcome}"/>
        </h:panelGrid>
        <h:form>
            <h:commandButton id="regresarBtn"
                             value="#{bundleMsg.pagina1_regresar}"
                             action="#{utilMB.navega('pagina1')}"
                             />
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/modulo1/Pagina1_v1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Pagina 1</title>
    </h:head>
    <h:body>
        <h1>Pagina UNO</h1>
        <h:form>
            <h:commandButton id="regresarBtn"
                             value="Regresar"
                             action="/index"
                             />
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/modulo1/Pagina2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{bundleMsg.app_title}</title>
        <h:outputStylesheet library="#{userSession.theme}" name="principal.css" />
    </h:head>
    <h:body>
        <h:panelGrid columns="2">
            <h:graphicImage id="logoImg" library="#{userSession.theme}"
                            name="#{bundleMsg.app_logo}"/>
            <h:outputText id="welcomeLabel" 
                          value="#{bundleMsg.pagina2_welcome}" />
        </h:panelGrid>
        <h:form>
            <h:commandButton id="regresarBtn"
                             value="#{bundleMsg.pagina1_regresar}"
                             action="#{utilMB.navega('pagina2')}"
                             />
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/modulo1/Pagina2_v1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Pagina 2</title>
    </h:head>
    <h:body>
        <h1>Pagina DOS</h1>
        <h:form>
            <h:commandButton id="regresarBtn"
                             value="Regresar"
                             action="/index"
                             />
        </h:form>
    </h:body>
</html>

CineArte/CineArte-war/web/vistaSala.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Configuracion Sala</title>
    </h:head>
    <h:body>
        <h:form>
            <h:inputText id="funcion" value="#{salaMB.idFuncion}"/>
            <h:commandButton id="mapaButton" value="Llenar" action="#{salaMB.preparaSala()}"/>
            #{salaMB.mapaSala.size()}
            <table>
                <c:forEach items="#{salaMB.mapaSala}" var="fila">
                    <tr>
                        <c:forEach items="#{fila}" var="asiento">
                            <td>
                                <h:commandLink 
                                    actionListener="#{salaMB.selectAsiento(asiento)}">
                                    #{asiento}
                                </h:commandLink>
                            </td>
                        </c:forEach>
                    </tr>
                </c:forEach>
            </table>    
        </h:form>

    </h:body>
</html>